Repository scholarslab/scholarslab.github.io, pull requests merged in 2018-05, with the labels that each got.

#175 Revert "Fixes #173"
  _research/bibliographic-society-of-virginia.md
  _research/collective-biographies-of-women.md
  _research/faulkner-at-virginia-an-audio-archive.md
  _research/for-better-for-verse.md
  _research/geoloader.md
  _research/jeffersons-notes-on-the-state-of-virginia.md
  _research/latvian-dainas.md
  _research/mapping-the-catalogue-of-ships.md
  _research/neatline.md
  _research/omeka-plugins.md
  _research/praxis-program.md
  _research/presidents-commission-on-slavery-and-the-university.md
  _research/project-blacklight.md
  _research/salem-witch-trials.md
  _research/solrmarc.md
  _research/spatial-search-and-delivery.md
  _research/speaking-in-code.md
  _research/the-falmouth-project.md
  _research/the-mind-is-a-metaphor.md
  _research/the-scholars-lab.md
  _research/the-university-of-virginia-art-museum-numismatic-collection.md
  _research/thl-place-dictionary.md
Labels: bug, content

#179 Incorporate prototype of person page
  _layouts/people.html
  assets/css/_sass/_flexible-nav.scss
  assets/css/_sass/_person.scss
  assets/js/main.js
  theme-testing/for-github.md
  theme-testing/screenshots/person-2.png
  theme-testing/screenshots/person-3.png
  theme-testing/screenshots/person-4.png
  theme-testing/screenshots/person-5.png
  theme-testing/screenshots/person-6.png
Labels: design, priority1

#181 Fix remaining issues in Research image names & YAML
  _research/bibliographic-society-of-virginia.md
  _research/collective-biographies-of-women.md
  _research/faulkner-at-virginia-an-audio-archive.md
  _research/for-better-for-verse.md
  _research/geoloader.md
  _research/jeffersons-notes-on-the-state-of-virginia.md
  _research/latvian-dainas.md
  _research/mapping-the-catalogue-of-ships.md
  _research/neatline.md
  _research/omeka-plugins.md
  _research/praxis-program.md
  _research/presidents-commission-on-slavery-and-the-university.md
  _research/project-blacklight.md
  _research/salem-witch-trials.md
  _research/solrmarc.md
  _research/spatial-search-and-delivery.md
  _research/speaking-in-code.md
  _research/the-falmouth-project.md
  _research/the-mind-is-a-metaphor.md
  _research/the-scholars-lab.md
  _research/the-university-of-virginia-art-museum-numismatic-collection.md
  _research/thl-place-dictionary.md
  assets/img/research/clickykbd-geoloader-thumb.png
  assets/img/research/tassiamohr-blacklight-banner.jpg
  pages/research.html
  pages/spatial-technologies.html
  theme-testing/for-github.md
Labels: bug, content, priority1

#184 Add missing people photos as per #59
  assets/img/people/andrew-carl.jpg
  assets/img/people/ankita-chakrabarti.jpg
  assets/img/people/ben-gorham.jpg
  assets/img/people/brandon-phan.jpg
  assets/img/people/catherine-addington.jpg
  assets/img/people/elizabeth-mitchell.jpg
  assets/img/people/julia-haines.jpg
  assets/img/people/katherine-donnally.jpg
  assets/img/people/lauren-reynolds.jpg
  assets/img/people/marysia-serafin.jpg
  assets/img/people/nic-dalton.jpg
  assets/img/people/ryan-maguire.jpg
  assets/img/people/sarah-berkowitz.jpg
  assets/img/people/spyros-simotas.jpg
  assets/img/people/tanner-greene.jpg
  assets/img/people/victoria-clark.jpg
  assets/img/people/zoe-leblanc.jpg
Labels: content, priority1

#200 Incorporate 1st draft of research project page layout
  _data/research.yml
  _layouts/research.html
  _starter-kits/networks.md
  assets/css/_sass/_research-project.scss
  assets/css/_sass/_research.scss
  assets/css/style.scss
  assets/js/main.js
  assets/python/html-to-css.py
  pages/research.html
  theme-testing/for-github.md
  theme-testing/screenshots/research-detail-1.png
  theme-testing/screenshots/research-detail-10.png
  theme-testing/screenshots/research-detail-2.png
  theme-testing/screenshots/research-detail-3.png
  theme-testing/screenshots/research-detail-4.png
  theme-testing/screenshots/research-detail-5.png
  theme-testing/screenshots/research-detail-6.png
  theme-testing/screenshots/research-detail-7.png
  theme-testing/screenshots/research-detail-8.png
  theme-testing/screenshots/research-detail-9.png
Labels: design, priority1

#202 Updates to research project gallery
  assets/css/_sass/_research.scss
  assets/css/style.scss
  assets/js/main.js
  corpus.json
  pages/research.html
  theme-testing/screenshots/research-gallery-3.png
Labels: design, priority1, structure

#203 Fix homepage
  assets/css/_sass/_home.scss
  assets/css/style.scss
  index.html
Labels: design, priority1, structure
